
// THIS CODE IS RUNNING ON THE FUNCTIONS EXECUTION CONTEXT SO MYVAR IS ATTACHED TO THAT FUNCTIONS SCOPE
function b() {
  var myVar
  console.log(myVar)
}


// THIS CODE IS RUNNING ON THE FUNCTIONS EXECUTION CONTEXT SO MYVAR IS ATTACHED TO THAT FUNCTIONS SCOPE
function a() {
  var myVar = 2
  console.log(myVar)
  b()
}


// THIS CODE IS RUNNING ON THE GLOBAL EXECUTION CONTEXT SO MYVAR IS ATTACHED TO THE GLOBAL SCOPE
var myVar = 1;
console.log(myVar)
a()
console.log(myVar)
// MYVAR IS 1 BECAUSE IT RESIDES IN THE GLOBAL EXECUTION CONTEXT/GLOBAL SCOPE